import { IHeadphone } from '@utils/types/IHeadphone'

export const headphones: IHeadphone[]  = [
  {
    id: 0,
    img: 'eearpods.png',
    title: 'Apple BYZ S8521',
    price: 2927,
    lastPrice: 3527,
    rate: 4.7,
    wireless: false,
  },
  {
    id: 1,
    img: 'earpods2.png',
    title: 'Apple EarPods',
    price: 2327,
    rate: 4.4,
    wireless: false,
  },
  {
    id: 2,
    img: 'earpods3.png',
    title: 'Apple EarPods Pro',
    price: 2327,
    rate: 4.6,
    wireless: false,
  },
  {
    id: 3,
    img: 'eearpods.png',
    title: 'Apple ZYB XL',
    price: 2127,
    lastPrice: 2527,
    rate: 4.4,
    wireless: false,
  },
  {
    id: 4,
    img: 'earpods2.png',
    title: 'Apple EarPods Max',
    price: 3327,
    rate: 4.6,
    wireless: false,
  },
  {
    id: 5,
    img: 'earpods3.png',
    title: 'Apple EarPro',
    price: 4327,
    rate: 4.7,
    wireless: false,
  },
  {
    id: 6,
    img: 'airpods.png',
    title: 'Apple AirPods',
    price: 9527,
    rate: 4.7,
    wireless: true,
  },
  {
    id: 7,
    img: 'gerlax.png',
    title: 'GERLAX GH-04',
    price: 6527,
    lastPrice: 7239,
    rate: 4.8,
    wireless: true,
  },
  {
    id: 8,
    img: 'borofone.png',
    title: 'BOROFONE B04',
    price: 7527,
    rate: 4.9,
    wireless: true,
  }
];
